[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1


[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "categories"
  name = "分类"
  url = "categories"
  weight = 3

[[main]]
  identifier = "about"
  name = "关于我"
  url = "about"
  weight = 4


